//
//  MeetingRoomModels.swift
//  CleanSwift_test
//
//  Created by Paul Jang on 2019/12/24.
//  Copyright (c) 2019 Paul Jang. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import SwiftyJSON
enum MeetingRoom {
     enum Time {
        struct Request {
            
        }
        struct Response {
            var time: String
        }
        struct ViewModel {
            var time: String
        }
    }
    
    enum Schedule {
        struct Request {
            
        }
        struct Response {
            var timeSchedule: JSON
        }
        struct ViewModel {
            var timeSchedule: JSON
        }
    }
     
    enum detailMeetingRoomCell {
        struct Request {
            var cell: DetailMeetingRoomCell
        }
        struct Response {
            
        }
        struct ViewModel {
            
        }
    }
    
    enum UiPositionCompletionHandler {
        struct Request {
            var cell: DetailMeetingRoomCell
        }
        struct Response {
           
        }
        struct ViewModel {
           
        }
    }
     
    enum TimeSet {
        struct Request {
            var json: JSON
        }
        struct Response {
            var timeBlockDic = [Int:Array<String>]()
            var availableRoom = [String]()
        }
        struct ViewModel {
            var timeBlockDic = [Int:Array<String>]()
            var availableRoom = [String]()
        }
    }
}
