//
//  MeetingRoomPresenter.swift
//  CleanSwift_test
//
//  Created by Paul Jang on 2019/12/24.
//  Copyright (c) 2019 Paul Jang. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MeetingRoomPresentationLogic {
    func jsonParse(response: MeetingRoom.Schedule.Response)
    func currentTime(response: MeetingRoom.Time.Response)
    func timeSet(response: MeetingRoom.TimeSet.Response)
}

class MeetingRoomPresenter: MeetingRoomPresentationLogic {
    weak var viewController: MeetingRoomDisplayLogic?
   
    func jsonParse(response: MeetingRoom.Schedule.Response) {
        let viewModel = MeetingRoom.Schedule.ViewModel(timeSchedule: response.timeSchedule)
        viewController?.jsonParse(viewModel: viewModel)
    }
    
    func timeSet(response: MeetingRoom.TimeSet.Response) {
        let viewModel = MeetingRoom.TimeSet.ViewModel(timeBlockDic: response.timeBlockDic, availableRoom: response.availableRoom)
        viewController?.timeSet(viewModel: viewModel)
    }
    
    func currentTime(response: MeetingRoom.Time.Response) {
        let viewModel = MeetingRoom.Time.ViewModel(time: response.time)
        viewController?.currentTime(viewModel: viewModel)
    }
}
