//
//  FavoriteListModels.swift
//  CleanSwift_test
//
//  Created by Paul Jang on 2019/12/23.
//  Copyright (c) 2019 Paul Jang. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum FavoriteList {
    enum favoriteModel {
        struct Request {
            var favoriteSelect: Any
        }
        struct Response {
        
        }
        struct ViewModel {
            
        }
    }
    
    enum CompletionHandler {
        struct Request {
            var id: String
            var tag: Int
        }
        struct Response {
           
        }
        struct ViewModel {
           
        }
    }
    
    enum listPreview {
        struct Request {
            let searchText: String?
        }
        struct Response {
            
        }
        struct ViewModel {
             
        }
    }
}
