//
//  FavoriteListWorker.swift
//  CleanSwift_test
//
//  Created by Paul Jang on 2019/12/23.
//  Copyright (c) 2019 Paul Jang. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class FavoriteListWorker {

}
