//
//  SearchUserListRouter.swift
//  CleanSwift_test
//
//  Created by Paul Jang on 2019/12/22.
//  Copyright (c) 2019 Paul Jang. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SearchUserListRoutingLogic {
    //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol SearchUserListDataPassing {
    var dataStore: SearchUserListDataStore? { get }
}

class SearchUserListRouter: NSObject, SearchUserListRoutingLogic, SearchUserListDataPassing {
    weak var viewController: SearchUserListViewController?
    var dataStore: SearchUserListDataStore?
  
  // MARK: Routing
  
//    func routeToSomewhere(segue: UIStoryboardSegue?) {
//        if let segue = segue {
//            let destinationVC = segue.destination as! SomewhereViewController
//            var destinationDS = destinationVC.router!.dataStore!
//            passDataToSomewhere(source: dataStore!, destination: &destinationDS)
//        } else {
//            let storyboard = UIStoryboard(name: "Main", bundle: nil)
//            let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
//            var destinationDS = destinationVC.router!.dataStore!
//            passDataToSomewhere(source: dataStore!, destination: &destinationDS)
//            navigateToSomewhere(source: viewController!, destination: destinationVC)
//        }
//    }

  // MARK: Navigation
  
//    func navigateToSomewhere(source: SearchUserListViewController, destination: SomewhereViewController) {
//        source.show(destination, sender: nil)
//    }
  
  // MARK: Passing data
  
//    func passDataToSomewhere(source: SearchUserListDataStore, destination: inout SomewhereDataStore) {
//        destination.name = source.name
//    }
}
