//
//  SearchUserListWorker.swift
//  CleanSwift_test
//
//  Created by Paul Jang on 2019/12/22.
//  Copyright (c) 2019 Paul Jang. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import SwiftyJSON

class SearchUserListWorker {
    
    func DBLoad() {
        SqlService.shared.searchAllData()
    }
        
    func dataCombine(remainData: [SearchUserList.listPreview.ViewModel.listPreviewData], searchResult: JSON) -> [SearchUserList.listPreview.ViewModel.listPreviewData]? {
        
        var dataList: [SearchUserList.listPreview.ViewModel.listPreviewData] = remainData
        for (_, value) in searchResult {
            let data = SearchUserList.listPreview.ViewModel.listPreviewData(id: value["id"].stringValue, avatar_url: value["avatar_url"].stringValue, score: value["score"].stringValue, login: value["login"].stringValue)
            dataList.append(data)
        }
        
        return dataList
    }
}
