//
//  SearchUserListModels.swift
//  CleanSwift_test
//
//  Created by Paul Jang on 2019/12/22.
//  Copyright (c) 2019 Paul Jang. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import SwiftyJSON

enum SearchUserList {
    enum listPreview {
        struct Request {
            let searchText: String?
        }
        struct Response {
            var searchResult: [Any]
        }
        struct ViewModel {
            struct listPreviewData {
                var id: String
                var avatar_url: String
                var score: String
                var login: String
            }
            
            var displayedData: [listPreviewData]
        }
    }
    
    enum favoriteModel {
        struct Request {
            var favoriteSelect: Any
        }
        struct Response {
        
        }
        struct ViewModel {
            
        }
    }
    
    enum CompletionHandler {
        struct Request {
            var id: String
            var tag: Int
        }
        struct Response {
           
        }
        struct ViewModel {
           
        }
    }
}
