//
//  SearchUserListCell.swift
//  CleanSwift_test
//
//  Created by Paul Jang on 2019/12/22.
//  Copyright (c) 2019 Paul Jang. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchUserListCellDelegate {
    func selectButtonClick(index: Int)
}

class SearchUserListCell: UITableViewCell {
    
    @IBOutlet weak var avatarImg: UIImageView!
    @IBOutlet weak var userName: UILabel!
    @IBOutlet weak var userScore: UILabel!
    @IBOutlet weak var favoriteStar: UIButton!
    
    var searchUserListCellDelegate: SearchUserListCellDelegate?
    
    override func awakeFromNib() {
        super.awakeFromNib()
        // Initialization code
    }
 
    @IBAction func favoriteButtonClick(_ sender: Any) {
        if searchUserListCellDelegate != nil {
            searchUserListCellDelegate?.selectButtonClick(index: avatarImg.tag)
        }
    }
}


